include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_specify_types: true
    avoid_annotating_with_dynamic: true
    combinators_ordering: true
    public_member_api_docs: false
    sort_pub_dependencies: true